name: fasila
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  go_router: ^16.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter 

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
