name: fasila
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  cloud_firestore: ^5.6.11
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  flutter_local_notifications: ^19.3.1
  flutter_localization: ^0.3.3
  flutter_paypal_payment: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.0
  flutter_time_picker_spinner: ^2.0.0
  geolocator: ^14.0.2
  go_router: ^16.0.0
  google_maps_drawing_tools: ^0.0.6
  google_sign_in: ^5.4.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  shimmer: ^3.0.0
  timezone: ^0.10.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:

  uses-material-design: true
  assets:
    - assets/
flutter_intl:
  enabled: true
