// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNUX8_f_TykQbXtt4fQ8XJgD324V3TadM',
    appId: '1:296333495392:web:2943cb0c207e2ac17c0705',
    messagingSenderId: '296333495392',
    projectId: 'fasila-b42dc',
    authDomain: 'fasila-b42dc.firebaseapp.com',
    storageBucket: 'fasila-b42dc.firebasestorage.app',
    measurementId: 'G-BH33Q56L4E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa7ugcsEwV2KC7pCUUoFDGg8rZ0VQfUOY',
    appId: '1:296333495392:android:b4bd10b5a79aa3ef7c0705',
    messagingSenderId: '296333495392',
    projectId: 'fasila-b42dc',
    storageBucket: 'fasila-b42dc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEaLR8tXV80PnmFgJkCj2EMOKGJW2NbqE',
    appId: '1:296333495392:ios:27a9207d585b37077c0705',
    messagingSenderId: '296333495392',
    projectId: 'fasila-b42dc',
    storageBucket: 'fasila-b42dc.firebasestorage.app',
    iosBundleId: 'com.example.fasila',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEaLR8tXV80PnmFgJkCj2EMOKGJW2NbqE',
    appId: '1:296333495392:ios:27a9207d585b37077c0705',
    messagingSenderId: '296333495392',
    projectId: 'fasila-b42dc',
    storageBucket: 'fasila-b42dc.firebasestorage.app',
    iosBundleId: 'com.example.fasila',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNUX8_f_TykQbXtt4fQ8XJgD324V3TadM',
    appId: '1:296333495392:web:e517cb140b3cbdb07c0705',
    messagingSenderId: '296333495392',
    projectId: 'fasila-b42dc',
    authDomain: 'fasila-b42dc.firebaseapp.com',
    storageBucket: 'fasila-b42dc.firebasestorage.app',
    measurementId: 'G-TEXRQP0WJC',
  );
}
